spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: sa
    password: password
    driver-class-name: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shareitH2
    username: sa
    password: password

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: DEBUG

