DELETE FROM comments WHERE id = 4;
ALTER TABLE comments ALTER COLUMN id RESTART WITH 1;

DELETE FROM items WHERE id = 3;
ALTER TABLE items ALTER COLUMN id RESTART WITH 1;

DELETE FROM users WHERE id = 1;
DELETE FROM users WHERE id = 2;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;