DELETE FROM bookings WHERE id = 4;
DELETE FROM bookings WHERE id = 6;
DELETE FROM bookings WHERE id = 7;
ALTER TABLE bookings ALTER COLUMN id RESTART WITH 1;

DELETE FROM items WHERE id = 3;
DELETE FROM items WHERE id = 5;
ALTER TABLE items ALTER COLUMN id RESTART WITH 1;

DELETE FROM requests WHERE id = 6;
DELETE FROM requests WHERE id = 4;
ALTER TABLE requests ALTER COLUMN id RESTART WITH 1;

DELETE FROM users WHERE id = 2;
DELETE FROM users WHERE id = 1;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
